/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_zengzhiying_JNIDemo */

#ifndef _Included_net_zengzhiying_JNIDemo
#define _Included_net_zengzhiying_JNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_zengzhiying_JNIDemo
 * Method:    testString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_zengzhiying_JNIDemo_testString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
